sudo: required

services:
  - docker

before_install:
  - docker build --rm=true -t gchiam/streamparse_quickstart .

script:
    - docker run gchiam/streamparse_quickstart --entrypoint "sparse" gchiam/streamparse_quickstart -h
